log:
  level: debug
  format: json

aws:
  region: "eu-west-1"
  endpoint: ""  # optional: set to override S3 endpoint (e.g. http://localhost:4566 for LocalStack)

milvus:
  local: false
  operator_name: "milvus"
  namespace: "milvus"
  username: ""
  password: ""
  root_bucket: "s3://milvus"
  root_path: "files"
  backup_bucket: "s3://milvus-backup"
  backup_etcd_path: "etcd-snapshots"
  backup_s3_path: "s3-snapshots"
